### ISSUE TITLE
Addition of Zoom/Meeting tools to Common Good Funding at the Funding Framework

### ISSUE THREAD

**Issue by rcscastillo** [ProgressiveCoders/functions#107]
There's been painpoints in setting up meetings for projects, hoping to add this to provide space for teams to schedule meetings via zoom.

Plan:

- create a partner-hub@progcode.org email
- create an event-type for Partners in Calendly. 
- Partners will have max of two hours per meeting. 
- They can schedule whenever they want
- We reserve the right to deny excessive scheduling (more than thrice a week).

**Comment by dave-mahler** [comment]
So how does this work with the Airtable calendar? are we now creating a different place for people to create events?

**Comment by rapicastillo** [comment]
I was hoping there would be an integration between airtable and calendly,
because calendly provides a scheduling solution. Will research on how info
from calendly can be incorporated

**Comment by dave-mahler** [comment]
Great!

**Comment by rcscastillo** [comment]
This has been added to the budget
