### ISSUE TITLE
Add to Decision Making Policy: notify people based on channel membership and consent-giving process.

### ISSUE THREAD

**Issue by rapicastillo** [ProgressiveCoders/functions#108]
Policies to add in the decision making process:

> EOD Saturday, @rapi will send an email of the agenda with all the items listed in the file. The people who will received the email will be the people who are in the #operations channel. 

> People will be able to put it to a vote to these through the google docs. They should not be anonymous and should put +1 / -1 / ~ as vote.

Four/Five days in advance issues should be there. Visibility. 
Extra step of courtesy: Extra trust building measure, posting in #operation 

This should be added in Wiki. Initially put in the google doc. 

Template form. 

+1 - Consent
-1 - No consent
~ - Pass/Abstain

**Comment by jpb5013** [comment]
Ah, shoot, just remembered after creating [this issue](https://github.com/ProgressiveCoders/functions/issues/124) that this one was already created. The issue I created includes the Google Doc mentioned above, let me know if I should merge that change with this one or modify in some other way.

**Comment by rcscastillo** [comment]
Moved to maintenance mode! Moved to standard change territory.
