### ISSUE TITLE
App Partner onboarders unable to access Medium to Publish "Network Voices"

### ISSUE THREAD

**Issue by WoobieTuesday** [ProgressiveCoders/functions#111]
### Proposed Solution

- Give App Partner Onboarding Team instructions on adding an App Partner's writing to "Network Voices"
- Give App Partner Onboarding Team Edit access to ProgCode Medium account

**Comment by jpb5013** [comment]
I'd add to this one that we also need to define what types of writing activities go into which channel or format.

**Comment by rapi-castillo** [comment]
Only thing we're not certain about is that all member onboarding facilitators are doing the pilot process the same way. Rapi, Dave, Pamela, Stephen.

**Comment by rapi-castillo** [comment]
could we do a wiki page for the instruction. So that it becomes an official thing. 

* It is an issue but it was not set to a WIKI because it's still in the process of beta testing.

It seems ready.

**Comment by rapi-castillo** [comment]
Stephen: Issue is the same as joe. Cannot plead ignorance because he was with joe, he has been with app creators in the last week. As he was trying to do it, it slowed it down so much, he was ready to go back to pen and paper, and do it again.

Set something up before tuesday's onboarding

**Comment by rapi-castillo** [comment]
Pamela: happy to do the call about how Pamela does it, just to give an idea on how to do it

**Comment by rcscastillo** [comment]
This should be good now. Have to do training on Pamela's end.
