### ISSUE TITLE
Create standard change template

### ISSUE THREAD

**Issue by jpb5013** [ProgressiveCoders/functions#112]
**Description**: Establish a standard GitHub change template to ensure consistent process and critical information captured, as defined in the [Change Process Wiki](https://github.com/ProgressiveCoders/functions/wiki/Change-Process)

**Problem**: We currently do not have a consistent way to implementing change, making it difficult for people to understand how to contribute to ProgCode functions

**Function**: Impacts all ProgCode functions

**Benefit**: A standard format will make contributing to ProgCode much more straightforward, predictable and impactful

 **Plan**: 

1. Pilot out with this issue as the initial use case
2. Gather feedback in #operations and update template accordingly to meet needs
3. Update current change process as needed, including linking to this change template

**Comment by desmondjones** [comment]
Should the discussion be limited to GitHub?  Would a different process be required for Airtable?

**Comment by jpb5013** [comment]
Ah, to clarify, any _changes_ we make should be documented as GitHub issues, regardless of whether the change impacts GitHub, Airtable or any other functional area. So this would drive consistency and uniformity around all of our changes.

**Comment by rapicastillo** [comment]
I'd like to forward the template I've used in #125

**Comment by jpb5013** [comment]
Ah, cool. I'd like to look at how do the two come together, though they
cover a lot of the same information. Having a more detailed plan I think
will be beneficial, as it makes sure people are thinking through all the
steps and impact, not just the vote side. Having the problem and benefit
the change addresses also helps ensure that we're focused on providing
underlying value.

**Comment by rapicastillo** [comment]
Yup! For me it's more on a lower barrier of entry. the deeper they present the description part the better people will be in learning more. So if we encourage folks to write more and be mindful on what they write, I feel that would be a good step forward than having lots of questions to answer.

**Comment by jpb5013** [comment]
Totally agreed. I think having the steps for the proposed plan forward
should be critical, other things can likely be rolled up into a
Description, which could include the problem and benefit as people see fit.
Trying to avoid continuously asking the same questions. This here
<http://www.businessballs.com/changemanagement.htm> is a pretty good
overview about change management. The principles (culture, if you will) is
ultimately more important than the steps, though steps should facilitate
culture.
