### ISSUE TITLE
Remote MeetUp Hack Night

### ISSUE THREAD

**Issue by jpb5013** [ProgressiveCoders/functions#116]
**Description**: Extend the in-person every other week hack night to online, enabling back-and-forther engagement 

**Problem**: In-person engagement is one of the best ways to connect with people, however it's inherently geographically constrained and the in person engagement isn't necessarily extended to online

**Function**:  Evangelism

**Benefit**: A connected in-person and online engagement will produce a positive feedback loop, resulting in increased member engagement, buyin and impact

**Plan**:

1. Pilot with every other week New York Hack Night
2. @tktino Plugging in with his laptop on Zoom
3. Capture best practices and learnings for extending into other areas

**Resolution**:
[Process created](https://github.com/ProgressiveCoders/functions/wiki/In-Person-to-Online-Engagement-Process) and updated the [Evangelism](https://github.com/ProgressiveCoders/functions/wiki/Evangelism) function

**Comment by rapicastillo** [comment]
Congrats!

**Comment by rapi-castillo** [comment]
Great first step. Talked to charlotte, extend the in person on line too, they will continue to work on those as we move forward. 

Had a lot of good idea, for the github issues to have a clear format

**Comment by rcscastillo** [comment]
ProgHackNight – to be posted in facebook.

**Comment by rcscastillo** [comment]
Will close this as it's more on maintenance?

**Comment by rcscastillo** [comment]
@jpb5013 ☝️
