### ISSUE TITLE
Update Volunteer Registration Form

### ISSUE THREAD

**Issue by jpb5013** [ProgressiveCoders/functions#123]
**Description**: Update the [Volunteer Registration Form](https://airtable.com/shraBEItZa0sYiMB0) to make it more representative of ProgCode goals

**Problem**: Volunteer registration form doesn't currently convey the core underlying goals for Prog Code (e.g., getting money out of politics), leading to a lack of focus

**Function**: Operations

**Benefit**: Will ensure new members are aware of our goals and focused on the core mission

Plan:
1. Update the sub-text to the question: "Why do you want to join the Progressive Coders Network?" from 

> In your own words, tell us a bit about yourself and what brought you to the Progressive Coders Network. An essay is totally ok here!

To:

> ProgCode is working to provide open source, grassroots organizing tools aiming to remove money's influence in politics. Please tell us a little bit about yourself, what brought you to ProgCode and how you'd like to support these goals.

2. Change "Contact E-Mail" to "Contact Email" and "Preferred E-mail address" to "Preferred Email address"

**Comment by jpb5013** [comment]
@jlegrone, I believe you said you wanted to have a look at this before posting the change. Let me know if you have any changes

@rapi-castillo, I'm not sure if I have permissions to update the original form, happy to do so if you can grant them.

**Comment by rcscastillo** [comment]
Have a quick discussion with Jacob. Not having permissions to have a quick look and any alterations.

**Comment by rapi-castillo** [comment]
Sent him invite.

**Comment by desmondjones** [comment]
A lot of applicants either neglect or refuse to provide information about themselves relevant to the the nexus between their desire to join ProgCode and our mission.  Some have outright let it be known that they don't intend to provide that information.  It would be helpful to address whether this is critical information for ProgCode to know before considering an applicant for membership.  Personally, I consider it important, because this is more than a social Slack environment.

**Comment by PamelaJohn** [comment]
Another thing to keep in mind when we proceed with updating the Volunteer Registration Form are potential needs for members of vulnerable or targeted communities for whom it may not be safe to provide private information (i.e., undocumented American immigrants, activists or individuals who work for the government).

I would love to get feedback from @l_arely on potential ways that HackTheBan has been able to screen/vet its Slack membership to ensure alignment of purpose while at the same time respecting the needs of individuals who are members of targeted communities.

**Comment by patcon** [comment]
Just wanted to chime in to say that I was one of those folks who wasn't clear on the tightly-focussed "money out of politics" mission :)

I definitely support it on its face, but will admit to wishfully thinking/hoping the mission were wider. I was really hopeful that ProgCode was shaping into being something of a [g0v-zero](http://g0v.asia/)-like force. I'm still VERY excited for what we all do in this space, but a strict scope tempers that a bit.

@rcscastillo Does ProgHacknight has a similarly scoped mission?

**Comment by jpb5013** [comment]
That's great feedback, Patrick, thanks! I always looked at money in
politics as the root of all problems with the solution addressing all of
the other needs people have raised, but I see how focusing on that seems a
bit narrow in scope and myopic. Believe me, I have BIG goals, so I'm
confident a wide variety of things are in scope.

We've been thinking a lot about this due to consistent feedback and
actually had a really great discussion on the topic during the 100k members
strategy meeting, notes available here:
https://docs.google.com/a/progcode.org/document/d/1LVmEnvOWp_LLUT8ZHRzADzJQRsub_JqRxnxvjigVctE/edit?usp=drivesdk

The quick answer is: in general, I agree. As noted in the meeting notes,
what I've been thinking about is "Democratizing Democracy," which would
include much grander things. At a high level, it's empowering the
grassroots and providing open source tools in addition to removing money in
politics. The spring/summer strategy on the progressive coder medium blog
also details this fairly comprehensively.

I'll probably come up with new language that I'll re propose because there
does need to be some guide rails due primarily to legal reasons, but I
would see us having more flexibility.

**Comment by PamelaJohn** [comment]
@jpb5013 @stephenscapelliti Can this issue now be closed?
