### ISSUE TITLE
Rapi is asking if he can accept the compensation offered by ACLU to him for the service rendered on the peoplepower map.

### ISSUE THREAD

**Issue by rapicastillo** [ProgressiveCoders/functions#125]
## Description

ACLU (through Kenneth Pennington) would like to compensate me (Rapi) for the service I have rendered for them in setting up the People Power map, seen here: ( map.peoplepower.org ). The gig is $60/hr, at 12 hours. 

I'd like to ask if this is kosher to the team. I am currently on the red (as I've been flying around the country for ProgCode), and since ACLU is able to fund these things, it could be helpful for me.

I am contracting with me directly, and the work is done outside of progcode.

## Who is affected

Ethics issue, precedent. May be other teams? Not sure

## Planned Vote

I'd like to take this to the community if the ops team consents

**Comment by rapicastillo** [comment]
Rachel:
I guess I don't understand bc I thought the people power map was a progcode thing. If this is entirely you outside of progcode then it seems weird to be asking for consent to get the $ and if it wasn't entirely out of progcode then from what little I know it seems like the $ would be best funnelled through progcode and back out to you.

[1:17]  
(Either way yes get the $!)

rapi [1:17 PM] 
yeah i just wanted to be completely transparent and check if this is kosher.


rachel [1:17 PM] 
Yup I know just starting a convo to lead us down a rabbit hole. :wink:

rapi [1:18 PM] 
:smile:

[1:18]  
here we go! :hole:

rachel [1:18 PM] 
Anyways that's my comment. :slightly_smiling_face:

rapi [1:18 PM] 
thanks Rachel!

[1:19]  
It was weird for me to add the expenses made this month, and the ACLU. But just wanted to share the out of pocket expenses I've made and I think it was weird to post that there since ACLU is not going to pay me for that

[1:19]  
i think it will be a separate issue then. (edited)

[1:20]  
there! https://github.com/ProgressiveCoders/functions/issues/127
GitHub
Recent Expenses for ProgCode (Out of Pocket) · Issue #127 · ProgressiveCoders/functions
For a run-down of the expenses made for ProgCode this past month. Please checkout this spreadsheet Just wanted this to be a part of the conversation.
 

rachel [1:21 PM] 
Yeah I def don't think anybody expects you to be paying out of pocket for this stuff on a perm. basis. Might be worth asking @desmondjones and the rest of #legal for the best way to do this for the purposes of the org finances?

[1:21]  
(There might be benefits to having some kind of cash flow going through progcode but I don't know what they'd be/if they exist.)

[1:22]  
(And to be clear even if you're being paid outside of progcode for the ACLU stuff, that's still an out of pocket expense for progcode expenses because the money isn't going in and out of the same pots. Like, technically these are progcode expenses, they should be coming out of a progcode budget.)

rapi [1:22 PM] 
Yes, i think that would be best moving forward

rachel [1:22 PM] 
(Meanwhile your pay from the ACLU is like...Rapi's money. Heh.)

**Comment by samuelcole** [comment]
imo: you are allowed to do freelance, even if it's for an app originated in progcode

i actual think it's more dangerous precedent to restrict people from doing freelance because of their experience at progcode.

**Comment by rapicastillo** [comment]
Thanks Sam! It's more about the fact that founded ProgCode and as the
current person leading it, I feel that this has to be put out and check if
it's kosher with everyone.

**Comment by desmondjones** [comment]
Thank you for asking the community to weigh-in on this Rapi.  I agree with both you and @samuelcole.
