### ISSUE TITLE
Queer Tech NYC (March 28)

### ISSUE THREAD

**Issue by rapicastillo** [ProgressiveCoders/functions#126]
We were asked to speak at the Queer Tech NYC Meetup on March 28.

**Comment by rapicastillo** [comment]
Asked to talk about ProgCode, projects (internal/external), way to recruit people to work on open source projects 
Also opportunity to find more allies
Benny influencing Rapi to work on more progressive technology :)
http://lgbtq.technology/
Tino definitely going to attend, let him know if anyone else is going

**Comment by rcscastillo** [comment]
Closing this as it has passed. [Great experience, and resonated well with folks](https://www.meetup.com/queer-tech/events/238475536/)
