### ISSUE TITLE
Add the Airtable Calendar to the ProgCode toolkit

### ISSUE THREAD

**Issue by dave-mahler** [ProgressiveCoders/functions#128]
**Description**: Add the Airtable calendar to the ProgCode toolkit.

**Problem**: If toolkit is where we're consolidating all helpful links, lack of calendar means people need to know where else to look.

**Function**: I'm not entirely sure what this header is for.

**Benefit**: Continues consolidation of important links for all members of the community

**Plan**: Add the Airtable calendar to the ProgCode toolkit.

**Comment by rapicastillo** [comment]
Sent you the perms for the Spreadsheet! Let me know if that works. I move for the contents of the toolkit be in the purview of trusted volunteer staffers, but be open to be pulled back.

**Comment by jpb5013** [comment]
I'd further that by describing this as a "standard change." We should still
have a record of it (maybe one long-lasting GitHub issue where changes are
updated and tracked, though shouldn't require the complete process for more
complex changes, as that will allow for the checks and balances of being
pulled back.

Love you using the format, Dave! The "Function" is used to describe what
function the change impacts. For many that we work on (like this) it will
probably be all functions, as the calendar is relevant to all functions.

**Comment by jpb5013** [comment]
I've updated the proposed "[Staff Change and Decision Making](https://docs.google.com/document/d/173GOBiB1NgibNTuLNkGTcC7BDDVM3mBQDIfA8iyum5o/edit#)" document  as described in [this issue](https://github.com/ProgressiveCoders/functions/issues/124) to reflect the proposed flow for a standard change. If approved, I proposed using this as the use case example for how we handle "standard changes"

**Comment by dave-mahler** [comment]
hey @rapi-castillo doesn't look like the calendar has been added yet. Want me to do it?

@jpb5013 yeah I think it will be good for us to get a better feel for standard changes vs changes that require the process. Glad this works as a test case!

**Comment by rcscastillo** [comment]
It has been added @dave-mahler !

<img width="1220" alt="screen shot 2017-03-17 at 3 07 47 pm" src="https://cloud.githubusercontent.com/assets/25762075/24058976/912bbf3a-0b23-11e7-8264-e742e848ace3.png">

**Comment by dave-mahler** [comment]
Great!
