### ISSUE TITLE
Meeting with Rhize

### ISSUE THREAD

**Issue by rapi-progcode** [ProgressiveCoders/functions#13]
Discussion and conversation about the work Rhize is doing and how ProgCode, Swimmy, and other applications can plugin.

[Rhize Website](http://www.rhize.org/)

**Comment by rapi-progcode** [comment]
Wednesday @ 3:30p EST with @tktino

**Comment by tktino** [comment]
wicked

**Comment by rapicastillo** [comment]
This was moved to next week @tktino

**Comment by rapi-progcode** [comment]
@tktino @rapi-progcode had lovely time! :)

**Comment by tinobedi** [comment]
Had so much insight, had a great time!
