### ISSUE TITLE
Progressive Hack Night NYC to be a separate entity from ProgCode

### ISSUE THREAD

**Issue by rapicastillo** [ProgressiveCoders/functions#130]
### Description

As we move forward, I move that the `Progressive Hack Night` be built separately and treated as a separate entity from ProgCode. Not only will it be sustainable, it allows for a new form of leadership from various acters who are more inclined to participate locally onto the fold.

There is a steering committee meeting nextweek of an amazing cast of New Yorkers, and I think it would be best to have that kind of energy and potential onto those folks in a clean slate than onboarding to our own entity.

Also, it allows for other groups to plug in as well. ProgCode can be a partner of it, the same way that RagTag, Tech Solidarity, and other orgs can.

### Affected

I feel evangelism would be affected by it, but just wanted to know from people how y'all feel about this as well.

### Plan

- [x] Create a steering committee
- [x] Write up a formal partnership agreement with ProgCode (if decided by both ends)
- [x] Create a consent vote for Progressive Hack Night NYC

### Vote

By Consent

**Comment by dave-mahler** [comment]
So if it's created as a separate entity, it seems like it would also be great to establish a partnership agreement to help funnel projects to ProgCode (should they decide it would be a good fit for them). I really like the idea of independent leadership, but I'd be nervous about not making some efforts to keep a semi-formal relationship b/w the groups.

**Comment by rapicastillo** [comment]
ProgCode is free to sponsor hacknights or any other projects. 
Chicago would have their own structure

**Comment by rapicastillo** [comment]
@dave-mahler Sounds like a good plan. I've updated and created a plan section in the description

**Comment by rapicastillo** [comment]
Henry: Would it be beneficial for hack night to remain under ProgCode umbrella?

* Rapi: Hack night would be considered a partner so would still be able to benefit and partner with us

ProgCode is free to sponsor hacknights or any other projects. 
* Chicago would have their own structure
* If we have funds, we can sponsor the hacknight.
