### ISSUE TITLE
IRC Bridge Enabling

### ISSUE THREAD

**Issue by tktino** [ProgressiveCoders/functions#131]
### About the group		
We're looking to reduce the ramp up to Prog Code for a lot of free software developers who may already be communicating via IRC. Slack is a great way for many industry programmers to collect, with very little ramp up... but a lot of free software contributers who share Prog Code's mission are very much tied first to free software, and already connected on the (very similar) IRC.	

### Who we're looking for		
We are looking to open the IRC bridge in the slack channel.

Slack already supports IRC bridging. This will be really easy:
https://get.slack.help/hc/en-us/articles/201727913-Connect-to-Slack-over-IRC-and-XMPP
(Unlike peering with an IRC server, authentication here is the same as it is for Slack, and does not allow impersonation, and can be restricted to TLS only).

@kitography

**Comment by rcscastillo** [comment]
This is done! Woohoo
