### ISSUE TITLE
Add Members Tab to Master Airtable

### ISSUE THREAD

**Issue by WoobieTuesday** [ProgressiveCoders/functions#132]
### Problem
- When Member Onboarding Coordinators meet members in a 1:1 onboarding session, there is no place for the coordinator to take notes to record information disclosed for purposes of engaging member with projects (their own existing projects, projects in conception phase or other ProgCode projects). Information discussed but not recorded:
  - Past work experience
  - Current skills
  - Volunteer Activities
  - Civic Interests
  - Skills member wants to learn
  - Skills member wants to offer to the community
  - Whether member has a project in conception or development
  - Member City/Time Zone
- No central location for note-taking means information gathered in 1:1 which would be valuable to the community, gets lost and we are not optimizing the 1:1 experience.
  - Increases ability to match volunteer opportunities to member interests
    - Decreased Member engagement
      - Higher likelihood that Member disengages from Slack
    - Decreased volunteer pool for projects
      - Higher likelihood projects do not get completed
  - Results in onboarding coordinators spending additional time searching for members whose skill sets meet the needs of app project partners

### Solution
- Add a tab to the Airtable Master List called "Members" which is accessible by Member & Partner Onboarding staff only
- Add the following columns to the Members Page in the Airtable Master List
  - Past work experience
  - Current skills
  - Volunteer Activities
  - Civic Interests
  - Skills member wants to learn
  - Skills member wants to offer to the community
  - Does Member have a project in conception or development
  - Member City/Time Zone

### Additional Notes from Mar 19 2017 Operations meeting 

- @rapicastillo Does not want to lose the interpersonal relationship and interaction between volunteer staff and new members
- @woobietuesday Seconded Rapi's observations in one-on-one contact and hope this form would not replace the interpersonal relationships and interactions between volunteer staff and new members, but would enhance engagement and deepen the relationship.
- @rthbound Just finished automating the process of updating the Master Airtable Channels listing. Would be a trivial thing to duplicate for the Members listing. Would take two days to incorporate existing membership data in automatically.
- Consent was given to implement adding a Members Tab to the Master Airtable and begin with manual procurement of data until Tad's automated solution is in place.
- Consent was also given to add this to the current onboarding process. 

[Tagging in @desmondjones @jpb5013 @tktino @progcodepreston @jlegrone @dave-mahler as additional volunteer staff on Member & Partner Onboarding Teams who should receive notice about this Change Process.]

**Comment by WoobieTuesday** [comment]
Thank you @rthbound for your quick response on this action item which received community consent during the Mar 19 Operations Team meeting!

@jpb5013 Just want to follow up to see whether I need to do anything to complete the last bullet point item "add this to the current onboarding process"?

**Comment by jpb5013** [comment]
Yeah, I think suggest any changes that we need to make to this Wiki. We
should review during next week's operations call
https://github.com/ProgressiveCoders/functions/wiki/Onboarding
