### ISSUE TITLE
Move Operations team meeting to Mondays @ 8pm ET

### ISSUE THREAD

**Issue by rapicastillo** [ProgressiveCoders/functions#135]
## Description

I move the operations team be moved to a monday, at around 7:30pm or 8pm ET.

## Problem

Sundays is usually not a good time, and it should be kept for rest and recharge. Respect to member self-care.

## Function

Whole operations team

## Plan

- [ ] Vote by consent.
- [ ] Start the operations team after March 26 to mondays. This will be effective April 3.

**Comment by jpb5013** [comment]
Should work for me! Hopefully I'll be living on the east coast by then :)

**Comment by tktino** [comment]
Works better for me, design meeting is by 8:30pm though.

**Comment by rcscastillo** [comment]
@tktino thanks for letting me know! I think from here on out, barring any emergency items, it will just last one hour a session, so that would mean 7:30pm is a good time too (added to choices).

**Comment by dave-mahler** [comment]
I teach Monday nights, so unfortunately I won't ever be able to make that time.

**Comment by rcscastillo** [comment]
It's done!
