### ISSUE TITLE
Standardize labels on github functions

### ISSUE THREAD

**Issue by dave-mahler** [ProgressiveCoders/functions#136]
### **Description** 

Labels are a really powerful organizational tool, and consistent use of labels will be an important component of streamlining communication between teams and members.

### **Problem** 

Labels are currently created at will, and there is not consistent use of labels by those creating issues, which is at least partly due to lack of a consistent system.

###  **Function**

Operation. All teams affected.

###  **Benefit**

Consistent use of labels helps better communicate to all people viewing the functions board.

###  **Plan**

1. Catalog existing labels.
2. Brainstorm possible ways to use labels.
3. 1 or more people propose labeling schemes, which will be voted on by the volunteer staff.
4. If volunteer staff decides that vote should be made by the community, then have a community vote.

**Comment by rcscastillo** [comment]
I'm removing much of the labels and only setting it to tools-and-documentation as it is the best fit.

**Comment by dave-mahler** [comment]
@rcscastillo seems like we've basically implemented this. Agreed to close this ticket?

**Comment by rcscastillo** [comment]
Sounds good!

**Comment by rcscastillo** [comment]
tagging this as standard change instead of by-consent
