### ISSUE TITLE
NYC Debug Politics

### ISSUE THREAD

**Issue by rapi-progcode** [ProgressiveCoders/functions#14]
Observe and Support people of Debug Politics as they engage with developers from New York.

Maybe wear a ProgCode shirt / giveout flyers.

[Debug Politics @ NYC – Jan 13-15](https://www.facebook.com/events/340431549650508/)

**Comment by rapicastillo** [comment]
This was a HUGE success! Amazing input and teamwork by everyone! Shoutout to @tktino @msimonborg @sean.mac @florida and the whole gang.
