### ISSUE TITLE
Restrict creation of private channels

### ISSUE THREAD

**Issue by dave-mahler** [ProgressiveCoders/functions#153]
#### Description
To make sure we are taking reasonable steps to prevent partisan activities from taking place on slack, we should restrict the creation of private channels by members.

#### Problem
To stay on the right side of the law as a 501(c)4, we need to minimize, if not eliminate, partisan or candidate-specific discussions / coordinated activities. Private channels are unregulated by staff members, and we cannot guarantee that improper activities are taking place.

#### Benefit
This change is consistent with the culture of the community (transparency) and, by making it easier for ProgCode to stay on the right side of the law, helps ProgCode continue to provide services to the community.
...

#### Plan

- [ ]
...

#### Decision Making

...

#### Reference link(s)

...

**Comment by jpb5013** [comment]
This is probably a good idea to explore, do you think this is what's contributing to the giant percentage of private messages lately? Question will be whether any are allowed, what the requirements/guidelines for creating one.

**Comment by dave-mahler** [comment]
I don't know that the two are necessarily related. I think we were a huge exception from the beginning when we had a high percentage of public messages. This is more related to us taking reasonable steps to limit partisan activity on the slack
