### ISSUE TITLE
Bi-weekly "ProgCode Nights" at ThoughtWorks

### ISSUE THREAD

**Issue by rapicastillo** [ProgressiveCoders/functions#16]
I will be reaching out to Duncan, our contact with TW, if we could use spaces in ThoughtWorks in a bi-weekly manner for ProgCode meetings at 6pm. 

This will follow the organizing process of Chi Hack Night, and invite ProgCode members in NYC, hoping that this will becoming a regular thing and be a model to different cities.

**Comment by jpb5013** [comment]
This is awesome! Excited to be returning to the east coast :) As I posted in Slack, I think it'd also be valuable to try to partner with existing Civic Tech nights that are in a bunch of cities

**Comment by rcscastillo** [comment]
This has now started! 

www.proghacknight.org 

And is now a separate entity from progcode.
