### ISSUE TITLE
Women's March on Washington

### ISSUE THREAD

**Issue by rapicastillo** [ProgressiveCoders/functions#17]
Representatives from the Women's March is in ProgCode, working with a lot of tech volunteers in helping the march organize and create tools that will help the people in going there, and coordinating.

They have officially added Progressive Coders Network in the list of [Partners](https://www.womensmarch.com/partners/), and we are continuously looking for ways to provide service.

Currently working on:

• Bus information - http://buses.womensmarch.com
• Resources - http://resources.womensmarch.com
• From Sam - http://www.marchbnb.com

**Comment by rapicastillo** [comment]
<img width="457" alt="screen shot 2017-01-08 at 2 02 56 am" src="https://cloud.githubusercontent.com/assets/399692/21747990/9cf8a4b2-d546-11e6-8b51-b01ac68b9baf.png">

**Comment by rapi-progcode** [comment]
Now working on the bus map!

**Comment by rapicastillo** [comment]
At the moment no additional requests. @rapi-progcode will go to Washington DC this weekend!

**Comment by rapi-progcode** [comment]
Helping out in looking for marshalls for the event.

**Comment by rapi-progcode** [comment]
Finished! We were able to keep both resources and bus-finder at the top 7 websites.
