### ISSUE TITLE
PhoneYourRep heroku prod hosting by ProgCode

### ISSUE THREAD

**Issue by dave-mahler** [ProgressiveCoders/functions#18]

**Comment by rapicastillo** [comment]
Dave, how's this doing?

**Comment by dave-mahler** [comment]
I'm not sure actually. I'll check with Matt, though I assume he would have said something if he was running into trouble.

**Comment by rapi-progcode** [comment]
@msimonborg how's this going? :) Anything we can improve on?

**Comment by danodemo** [comment]
Hey ya'll, PYR issues are being tracked on the PYR github now and no longer need to be tracked here :)  We can close this issue now!

**Comment by rapicastillo** [comment]
@dave-mahler from the recent activities here please let me know if it's safe to say you'll be an advocate for Phone your rep in the network
