### ISSUE TITLE
Give @progcode.org to Dave

### ISSUE THREAD

**Issue by rcscastillo** [ProgressiveCoders/functions#194]
#### Description

Dave has been advising a lot of applications, leading onboarding calls, and been a leader of the community.

Dave has been a volunteer staffer since the beginning of ProgCode. He has led the morning onboarding for since we've started the morning onboarding. I think it'd would be a great perk of ownership and engagement for Dave to have an account, and be able to use @progcode.org

Dave has also been advising and coordinating with application leaders, consulting and advising Phone Your rep and Swimmy, among others.

He has been on most of the operations staff meeting as well since December, when it was still done during Sunday. And has been a great partner in building out the tools for ProgCode.

#### Plan

- [ ] Consent
- [ ] Give Dave an @progcode acccount
...

#### Decision Making

...

#### Reference link(s)

...

**Comment by jpb5013** [comment]
Surprised he doesn't already have one. 100% in favor

**Comment by rcscastillo** [comment]
We need to have a more transparent and clear guidelines on how and when an individual can be alloted benefits. I'd like to apologize to Dave for having this done haphazzardly. Thanks! :)
