### ISSUE TITLE
Weekly Updates

### ISSUE THREAD

**Issue by rapi-castillo** [ProgressiveCoders/functions#2]
## Problem

The engagement in the Slack community is going too fast which results to people not having any idea on what's happening in the community.

## Solution

A weekly update that will tell the members and the public at large about the week that ProgCode has had.

## More Details

Leads/Writers:

* Rachel B.
* Dan N.
* Preston L.

**Comment by rcscastillo** [comment]
This has not stuck. Thanks for trying y'all! :)
