### ISSUE TITLE
Political Game Night development – Election Simulation

### ISSUE THREAD

**Issue by rapi-castillo** [ProgressiveCoders/functions#21]
Conceptualized with @mcruggs make a game that simulates an election between a heavily moneyed interest, and a grassroots star-eyed individual. First game night target: January 26. Game nights happen every last thursday of the month.

## Success Metric

We will have the viewers set as voters. Every milestone (there are 4), we will have a randomized poll of the viewers. 

### Moneyed Candidate

* Would have a lot of money
* More Staff
* Access to polling ( can poll viewers more than the grassroots candidate)
* Access to resources
* Access to more commercials
* Will get 70% of the players as staff
* Will initially have 70% of the vote

### Grassroots Candidate

* Would only have ProgCode applications
* Would only have 30% of the staff
* Would have an initial 100 volunteers
    * Note: candidate will only always have 20% of their Volunteers do basic campaign work
* Will initially have 30% of the vote

**Comment by mcruggs** [comment]
## **Moneyed Candidate**

- Works only for key constituencies
- Has a legislative history and responsibilities
- Has a list of questionable donations
- Access to media 
- Has Access to "Political Stars" as allies
- Not an inspiring speaker

## **Grassroots Candidate**

- Honestly works for the welfare of voters
- Has access to "Grassroots Stars" as allies
- Has more time to individually invest in election
- Is a persuasive and inspiring speaker 

## **Voters**

- Maybe slated as a pool of randomized interests mostly unknown to candidates?
- A large percentage will be apathetic to democratic process, but favor **Grassroots**
- A small percentage will be labeled "super voters," but favor **Moneyed**
- Many apathetic voters are struggling in difficult economic times with limited free time to invest 
- Motivated by real physiological factors 

## **Campaigning District**

- Each simulation should be drawn from real world districts, from state legislators to presidential primaries.

**Comment by rapi-progcode** [comment]
@mcruggs ! Want to go at it again? 👍  Would love to brainstorm again! :)

**Comment by rapicastillo** [comment]
No Movement on this, removing from column

**Comment by rcscastillo** [comment]
This did not stick! :) Closing
