### ISSUE TITLE
Add Multi-Select Airtable Column for Use by Project Onboarding Team

### ISSUE THREAD

**Issue by PamelaJohn** [ProgressiveCoders/functions#210]
**One change the community is seeing is an increased awareness of the services ProgCode provides to app project leaders** which are being developed or have already launched their first generation product. More frequently, **ProgCode is onboarding projects which are already live** but are in need of a bit more non-coding assistance to bring the project to full post-production potential.

Simultaneously, the services the ProgCode community envisions offering its app project partners on the community's path to sustainability are becoming more clearly defined.

## Current App Project Onboarding Interview Process
- Onboarding team interviews team lead(s) in 1:1
- Onboarding team records pertinent details in [Airtable Project listing](https://airtable.com/tblbgIV4Z5WxaEfTX/viwTFSaJ1RVs1syfD)
  - App Project needs are recorded in the "Needs" column which is presently a multi-line narrative format
  - Airtable Project listing is front-facing, and accessible via ProgCode website by:
    - App Project Onboarding Volunteer Staff
    - App Project Development Team
    - Public via ProgCode 

#### Suggest Adding Multi-Select "Needs" Column to the Airtable Project Listing
It could be helpful for project onboarders to further summarize the descriptive narrative needs list into have a broadly categorized, multi-select column in the Airtable Project Listing (similar to the tech stack column) for app leaders' needs (i.e., beta testing, legal, copy writing, marketing, etc.). The multi-select needs list would exist in the right hand column alongside the existing narrative description of needs. 

#### Potential Community Benefit To Adopting This Addition

1. An additional multi-select column alongside the existing narrative needs column **would allow the project list to  be sorted/filtered by needs** and could assist future teams of volunteer staff working to provide a specific member service (e.g. legal, or marketing) by **streamlining the search for projects in need of the expert services** volunteer staff have to offer. This may seem like a minor addition now, but as the community scales, it would definitely be valuable. 

2. It would take me less than 5 minutes to make the addition and would cost ProgCode $0. 

3. This addition would positively impact ProgCode's core objective of reducing the influence of money in politics through the creation of open source software by making the project onboarding process more efficient once ProgCode begins to offer member services to its app project leaders in accordance with its Manifesto. 

#### Decision Making
I don't think this change would impact any community members or projects outside of the app project onboarding team. Therefore, this issue is probably not a matter for which broader community consent is required. 

@desmondjones @jpb5013 @rapicastillo are current members of ProgCode's app project onboarding team. Please let me know if any of you have an objection to adding a multi-select "Needs" column to the right of the existing narrative "Needs" column? 

Please let me know if you have any questions or concerns! Thanks!

#### Reference link(s)
[Airtable Project Listing](https://airtable.com/tblbgIV4Z5WxaEfTX/viwTFSaJ1RVs1syfD)

**Comment by desmondjones** [comment]
As I mentioned in the #onboarding channel, this will facilitate a lot of the information which new members in onboarding sessions have said would be useful to them.  I agree that the proposed change is not one that needs to be brought up for a community vote.

**Comment by PamelaJohn** [comment]
After discussion among the partner onboarding team in the the community operations meeting tonight (7/31/2017), it was decided that this change did not need consent given all effected team members were notified per the Change Process and, agreed that the change would be beneficial.

On 7/31/2017, I added a new multi-select "Needs Categories" column to the right of the existing "Needs & Pain Points - Narrative" column.
