### ISSUE TITLE
Fix Bad Link in Calendly Onboarding Confirmation Email

### ISSUE THREAD

**Issue by PamelaJohn** [ProgressiveCoders/functions#233]
#### Bad Link in Calendly Onboarding Confirmation

When members sign up to attend a New Member Onboarding (from the website, Toolkit & Airtable Volunteer Slack registration form), Calendly settings automatically send confirmation and reminder emails. Confirmation and reminder emails contain an old Zoom link which was not updated at the time the community began using Stephen's paid Zoom account in place of Rapi's.  

The onboarding team was first notified of this problem in September 2017. I found the bad link in the reminder email and replaced it with [the good link](https://zoom.us/j/748696679), but did not check the confirmation email. The problem was again brought to my attention at the March 8th onboarding: the confirmation email _also_ contained a bad link. So much time had elapsed that between the September 2017 fix and the March 2018 fix, that Slack messages notifying the Onboarding team of the solution had been archived. 

This issue is being created to permanently log the procedure and process for fixing the Calendly link issue in the event the [New Member Onboarding link](https://zoom.us/j/748696679) changes in the future.

#### Problem
Bad links in confirmation and reminder notification emails mean new members are unable to join the Onboarding they signed up to attend. This could be a waste of time for new members and may result in confusion, or feelings the community is being poorly managed. Worst case scenario, new members disengage and do not reschedule and complete the very important New Member Onboarding process.

#### Benefit
Fixing this issue will streamline the onboarding process, be less confusing to new members and will better reflect professional community operations and management. 

#### Instructions for Updating Calendly Email Notification Settings
- [ ] Log into Calendly with admin email account + the password. (DM Operations Staff on Slack to obtain password.)
- [ ] Select `Dashboard` 
- [ ] Select `Progressive Coders Network Onboarding` recurring meeting
- [ ] Select `Edit`
![image](https://user-images.githubusercontent.com/24970546/37377471-bce9ee7e-26ef-11e8-9f76-e1e73d7aecbd.png)

- [ ] Select `Invitee Notifications`
- [ ] Select `Email Confirmations` and/or `Email Reminders`
- [ ] Select `Personalize`
![image](https://user-images.githubusercontent.com/24970546/37377559-4000b842-26f0-11e8-8eb7-a153122bdd6a.png)

- [ ] Replace the Calendly link in the body of the email
- [ ] Save changes
![image](https://user-images.githubusercontent.com/24970546/37377669-f3fe1fec-26f0-11e8-8104-c7edad557e7c.png)

#### Reference link(s)
[Current Calendly New Member Onboarding Link](https://zoom.us/j/748696679) as of 3.13.2018

**Comment by stephenscapelliti** [comment]
Fantastic, @PamelaJohn!  Having spent a couple of hours in the past testing and trying different options, this is helpful. Thank you.
