### ISSUE TITLE
MoveOn Grant

### ISSUE THREAD

**Issue by stephenscapelliti** [ProgressiveCoders/functions#235]
#### Description
MoveOn, a network partner of ProgCode, has graciously offered to Progressive Coders Network a grant in the amount of $10,000.  The grant agreement includes the following terms:
- "The Organization will use the Granted Funds solely to: Support the general purpose of the organization."
- "The relationship of the parties shall be that of grantor and grantee. Neither party shall have the right or authority to incur any obligation on behalf of the other party without the express prior written consent of the other party. This Agreement shall not be deemed to establish a joint venture or partnership, principal agent or employer-employee relationship between MoveOn and the Organization."
- Within 14 days of the 05-24-18 effective date of the agreement, MoveOn will make the grant to ProgCode.  The agreement term expires 12-31-18. Inasmuch as ProgCode has not yet signed the agreement, it is anticipated that the 14-day period will commence upon submission of the signed document.

#### Purpose of this Issue
- This issue is being opened to provide formal notice to the ProgCode community of the grant agreement, in accordance with the standard change process.
- Previous community discussions included a suggestion that donations in the amount of $10,000 and above from a non-profit 501(c)(4) entity be disclosed to the community. Although the criteria was not adopted as part of the change process, the staff feel that the source and amount of this particular grant are significant enough to that this discretionary criteria should be considered in this instance.

#### Benefit
This grant will enable ProgCode to fund current activities as well as some additional activities discussed in various meetings over the past 18 months.  A portion of the funds can be devoted to additional fundraising activities.  Proposals for use of the funds will be discussed in Community Operations meetings.  This pilot initiative relates solely to acceptance of the grant.

#### Plan
- [x] Post notice of this initiative in the #team-announcements, #wg-progcode-funding, and #operations Slack channels, together with instructions that all comments, questions, and objections to this pilot initiative may be recorded in the spaces below.
- [x] Post a link to recording of the 06-04-18 Community Operations meeting in which this subject was discussed in the #operations Slack channel.
- [x] Provide a 72-hour period for all ProgCode community members to submit comments, questions, and objections, if any.
- [x] Enable community members to view the grant agreement during the 72-hour notice period, upon request to the staff. Unless and until the grant agreement is executed, the document will not be made available in a public forum.

#### Decision Making
- [x] This issue is opened as a [standard change](https://github.com/ProgressiveCoders/functions/wiki/Change-Process) item.
- [x] Implement and execute the grant agreement upon approval of this standard change by 65% of the volunteer staff members, following the 72-hour community notice period. The Grant Agreement was discussed during the 06-04-18 Community Operations meeting, and staff unanimously consented to accept the agreement.

#### Reference link(s)
- [06-04-18 Community Operations meeting notes](https://docs.google.com/document/d/1BYcO0I871VNZk3QZjJhiBpS1zkh6ScyWA1CUtpOoigY/edit#heading=h.2arh4ddwsua7).
- [Funding Framework #81](https://github.com/ProgressiveCoders/functions/issues/81)
- [Implement Four-Pronged Test for Changes/Proposals to Guaranty Furtherance of ProgCode Core Objective & Legal Compliance #198](https://github.com/ProgressiveCoders/functions/issues/198)
- [Change Process Wiki](https://github.com/ProgressiveCoders/functions/wiki/Change-Process)

**Comment by joemcl** [comment]
This is great news!
