### ISSUE TITLE
Opportunity to Moderate a Netroots Nation 2018 Progressive Tech Caucus

### ISSUE THREAD

**Issue by PamelaJohn** [ProgressiveCoders/functions#239]
July 19, 2018, ProgCode received an invitation from Netroots Nation to propose a caucus of our choosing. ProgCode NN18 attendees in the #nn18 channel put together a caucus proposal for:

>A caucus of tech and non-tech activists who are committed to working together to achieve one goal: reduce the impact of big money in politics by creating open source tech to empower grassroots movements.

July 27, 2018, Denise Heitzenroder of NN18 wrote to advise they'd received two progressive tech caucus requests in addition to ours: one from Dan Ryan at Ragtag and another from ProgCode member Anna Jamborcic and Noah Levinson of Social Roots. Because caucus space is at a premium Denise emailed all of us and asked if we'd be willing to combine for one big caucus.

The topic proposal for the combined group is more broad than ProgCode's original suggestion, but is still mission aligned. The title of the caucus is *[Progressive Tech Caucus](https://www.netrootsnation.org/nn_events/nn18/progressive-technology-caucus/)*. Subject matter:

> How to be a good tech volunteer and how to use tech volunteers effectively. Tech and organizing. Share best practices people have found on how they organize their groups, and get volunteers to action. How do people use various organizing tech and what can we learn from each other?

The caucus is scheduled for **Friday, 8/3 from 4:15pm-5:30pm** (That's Session 7 on @baisong's [Spreadsheet](https://docs.google.com/spreadsheets/d/13iOcLjHZ_ncnER5-6afOq_7DKvLeDvF5LbW86RNiglw/edit#gid=0)).

#### Benefit
In addition to the "Open Source Tech #FTW" panel moderated by Shaka Lee, a progressive tech caucus moderated by ProgCode will be an excellent opportunity to broaden the community's reach at NN18!

#### Decision Making
Seeking Consent to Implement ProgCode being one of four moderators at the Netroots Nation 2018, Progressive Tech Caucus being held on Friday, August 3rd from 4:15 - 5:30pm.

#### Reference link(s)
[Progressive Tech Caucus](https://www.netrootsnation.org/nn_events/nn18/progressive-technology-caucus/)

**Comment by stephenscapelliti** [comment]
This is a great opportunity for ProgCode to promote our mission and the grassroots movement which is changing the face of government.

**Comment by baisong** [comment]
👍

**Comment by PamelaJohn** [comment]
Thanks everyone!!
