### ISSUE TITLE
Create a ProgCode Staff Manifesto

### ISSUE THREAD

**Issue by rapi-castillo** [ProgressiveCoders/functions#25]
A way to let Staffers know everything to know how, why, and what it is to become a progcode staffers.

Shared vision, shared goals.

**Comment by danodemo** [comment]
Already working on this.  Gonna make a fancy PDF using MacDown.  I'll post first draft here!

**Comment by rapicastillo** [comment]
@danodemo Would you mind if I add in to the manifesto? I'd like to add the ego check in it as well. :)

**Comment by rcscastillo** [comment]
This has been done through the Staff Handbook.
