### ISSUE TITLE
Arranging Meetings for Ana in Spain

### ISSUE THREAD

**Issue by rapicastillo** [ProgressiveCoders/functions#28]
Ana is in Barcelona to meet with a huge workers cooperative for SocialRoots. Wanted to insert meetings with political parties and movements in Spain, such as Podemos, Los Indignados, and Partido Socialista.

| Group Name | Contact | Status |
|- |- |- |
| Los Indignado | Biro via Jerome | Responded – Arranging |
| Podemos |   Biro via Jerome | Responded – Arranging |
| Partido Socialista | ___ via Alberto | Repsonded – Arranging? |

**Comment by rapi-progcode** [comment]
Alberto's Responded!

**Comment by rapi-progcode** [comment]
Susa has also responded

**Comment by rapi-progcode** [comment]
Ana has met with Hector from ThoughtWorks!

**Comment by rapi-progcode** [comment]
@ajamborcic Would you be free to do a debriefing this week?

**Comment by ajamborcic** [comment]
i can, but i'm not sure there's much to say other than Bojana (Socialroots) will do a presentation for thoughtworks about progcode and socialroots on feb 14(or 16 can't remember now).  they were generally supportive of what we're doing but it was unclear exactly how either of those things fit into their current work.  i will extend the invite for that meeting to anyone in progcode who wants to attend as well.

**Comment by rapicastillo** [comment]
That sounds fantastic thank you

**Comment by rapi-progcode** [comment]
@ajamborcic will be sending invites
