### ISSUE TITLE
Meeting with CivicHall about Show and Tell sessions infront of partners

### ISSUE THREAD

**Issue by rapicastillo** [ProgressiveCoders/functions#29]
Will be meeting with Veronica from Civic Hall tomorrow, Jan 19 at 6:30p EST to discuss about doing interviews and show and tells on the works Progressive Coders have done to the people in Civic Hall. This is some 30+ organizations residing in the common space.

**Comment by rapi-progcode** [comment]
Connected with #43 If I were to send in some preliminary docs then we should be good to go.

**Comment by rapi-progcode** [comment]
I will formulate this with Jacob Legrone

**Comment by rcscastillo** [comment]
this conversation has already started. Will build another issue if things progress (for approval)
