### ISSUE TITLE
Prog Bot - The ProgCode Slack Bot

### ISSUE THREAD

**Issue by danodemo** [ProgressiveCoders/functions#32]
Please submit change requests and offer feedback on our friendly Robot Overlord through this issue.

**ProgBot** is currently built with Python, and lives on Heroku

**ProgBot** was first brought online by _Pat Shea_ and _Dan Nicodemo_ in October 2016

## Current ProgBot Welcome Message:

Greetings, activist, and welcome to the Progressive Coders Network!

I have been programmed to share critical information with you about this place and our process. To begin, please take a glance at our *community guidelines* here:
http://bit.ly/2adB1mX

Once you have processed that information, feel free to explore our Slack.  A few of the channels you are already a part of include:  
- #jobs-and-vols - Ready to jump right in and start building?  Go here to see who needs immediate help!
- #pitch-zone - Have an idea for a project or initiative?  Post it here!
- #ask-the-team - Need to speak with someone in charge?  Ask here!  
- #call-to-action - When the movement has needs, they call to action here
- #mentoring - For more code assistance and 1-on-1 counsel.

Want to learn more about how to help from the team, and get a greater understanding of our process?  Join us Tuesday's for our weekly Onboarding Call (Hosted via the ZOOM app - http://zoom.us ) and get a briefing straight from the leadership team! When you're ready to take the next step into activism, sign up for an onboarding session here: https://goo.gl/hdhQkP

If you find yourself needing to reference any of this information, check out our wiki on Github, where you can also find information on issues that need volunteers, as well as everything you need to know about being a member of the community: https://github.com/ProgressiveCoders/functions/wiki

You're ready now: please feel free to introduce yourself to the community in #introduction!

**PLANNED FEATURES**
- Ability to add an event to the calendar directly from slack by sending it to ProgBot

- A glorified Help-Desk service, wherein ProgBot will automatically answer certain questions

- The ability to archive and save critical messages by asking ProgBot to archive them

- Better Tutorial/New User message system

**Comment by dave-mahler** [comment]
2 proposed changes:
1) mentoring is not being actively used by the community. We should replace it or just remove it from the list.
2) we should add a link to the master channel list, for those who want to find out about more than just the channels we list.

**Comment by rapi-progcode** [comment]
@danodemo would it be ok if we make the title more descriptive so fiolks will have better context and easy to plugin?

**Comment by dave-mahler** [comment]
Dan - here's the new link to the Master Channel list: https://airtable.com/shruhGsBZDvAZ2YMm

**Comment by rcscastillo** [comment]
Closing! For Dolores Landingham

**Comment by jake3030** [comment]
This project has been moved to https://github.com/rmd6502/progbot/

Please check that out and add new issues there.
