### ISSUE TITLE
Conversations with Rich @ Feb 9 • 8pm EST

### ISSUE THREAD

**Issue by rapi-castillo** [ProgressiveCoders/functions#42]
Rich was gracious to provide more insights about the flat structure that has propelled Loomio and Enspiral. Questions and learning about decentralized structures. 

Target date: Feb 9

Prerequisite: Watch [Six circles of Harmless Organizing](https://www.youtube.com/watch?v=b9ar0HVzNeE)

**Comment by rapi-progcode** [comment]
This has been set at Feb 9, 8pm!

https://actionnetwork.org/events/cultural-forms-to-organize-without-bosses

**Comment by dave-mahler** [comment]
@rapi-progcode should this issue be closed?

**Comment by rapicastillo** [comment]
Yup. It went great
