### ISSUE TITLE
Feb 6 - 10 Focus: Optimize Cultural Onboarding

### ISSUE THREAD

**Issue by rapi-castillo** [ProgressiveCoders/functions#56]
This week, and the probably the next, we need to find ways in order to optimize and make clearer the process by which a person is quickly onboarded to the ProgCode culture.

This will be very important as we see the influx of volunteers coming in.

**Comment by ajamborcic** [comment]
i believe this is largely being done by the on-boarding team being led by @jpb5013

**Comment by rapi-progcode** [comment]
Indeed, would like to encourage to have this idea at the back of our heads as we move through our respective areas as well.
