### ISSUE TITLE
Indivisible Group

### ISSUE THREAD

**Issue by rapi-castillo** [ProgressiveCoders/functions#63]
## ProgCode support for Indivisible

https://docs.google.com/document/d/10aL2wu5jje8LvkOEZBuYZbvBT7mPEDyrj9S5yFehGio/edit?usp=sharing

**Comment by rapi-progcode** [comment]
- [ ] Created Channel
- [ ] Added Documentation

**Comment by rapicastillo** [comment]
Site is up: https://www.indivisibleguide.com/groups-nav

**Comment by rapicastillo** [comment]
<img width="1434" alt="screen shot 2017-02-16 at 10 56 35 am" src="https://cloud.githubusercontent.com/assets/399692/23102834/71de62fe-f67e-11e6-8cba-6d423bddaaf4.png">

**Comment by rcscastillo** [comment]
This has been transferred to them, working with them now.
