### ISSUE TITLE
Weekly Content Calendar

### ISSUE THREAD

**Issue by dave-mahler** [ProgressiveCoders/functions#65]
As a staff member I want to add content to the calendar so that I can share this information with the community in #team-announcements

@WoobieTuesday and @rapicastillo are working together to formalize weekly content delivery.

Please feel free in filling out: https://docs.google.com/spreadsheets/d/1N7Ab-292rs8wm44QgetbsqwlpgKlnKZ0QVuRkjtJacc/edit#gid=191084811

Bonus: Weekend Free-for-all

We are all invited to pushing content during the weekend however we want. On Weekdays though, we need to be centered on the content calendar.

**Comment by WoobieTuesday** [comment]
@dave-mahler @progcodepreston re "pushing content"

> Bonus: Weekend Free-for-all
> 
> We are all invited to pushing content during the weekend however we want. On Weekdays though, we need to be centered on the content calendar.

Do we need to place limitations on the terms "free-for-all" and "however we want" to make sure that content is in compliance with [Community Guidelines](https://docs.google.com/document/d/1coMHvuGf6x6Qn_73SEhOXi_QaoRBM__3Zj6_5TyrmWs/edit) and the [Social Media Guidelines](https://docs.google.com/document/d/1PvkI6AU6xeVC_MOS0i4qp1nKkKQnWVwUSW6eEPNiArY/edit)? 

Also who is the intended audience for "we are all invited"? 

- staff w/admin access to #team-announcements
- members/partners/staff who write Medium pieces
- members/partners/staff who want to post on ProgCode Facebook and Twitter accounts? 

It seems to me that these things need further defining.
