### ISSUE TITLE
Reachout to Application Partners

### ISSUE THREAD

**Issue by rapi-castillo** [ProgressiveCoders/functions#68]
## Goal

To be able to reach out to all application leaders. Pair up with a new staffer as well :)

We want to keep them updated and involved in what's happening in ProgCode. So a personal time will be great.

### Conferences. 

* March: San Francisco, Washington DC , Chicago, NYC (Thought Kibbutz?)
* April: Debug Politics – Partnership
* June: Personal Democracy Forum (NYC) 

### Partnerships.

* Women's March
* Lawyers for Good Government
* Indivisible Groups
* Piece on the Village Voice
* Piece on Mother Jones

| Lead | Assigned to | Partner Updates |
|-- |-- |-- |
| 5Calls | Stephen | |
| Abortion Access - Ddmeraz | Pamela | *Follow-up Sent* |
| AlwaysForwardUs - Dan | Pamela/Joe | Mar 2 • 11am PT |
| BundleKind | Stephen | |
| Call Them - Matt Hindman/Whys | Pamela | _Reached out to schedule_ |
| CallParty - Kelseyah | Stephen | |
| CallYour - Jackson Hyland-Lipski | Pamela/Dan | *Send Follow Up Feb 17*  |
| Carpool Vote | Rapi | Done | 
| ClownStick - LAW | Stephen | |
| CodeCorps | Rapi | To Reachout |
| Crowd Count | Stephen | |
| EveryoneVote | Stephen | |
| Grassroots PB - Laksh | Stephen | |
| Grassroots PB - Sean | Rapi | Friday 7pm |
| Hack The Ban - Leslie/Sryia | Pamela | *Send Follow Up Feb 27* |
| Issue Voter - Maria | Rapi | Feb 16 • 5:30pm – 6:30pm |
| Knock Every Door - Hilary  | Stephen | | 
| Maps for Change - Anthony H | Rapi  | |
| Maps for Change - Deepak | Rapi | Today |
| Movement | Stephen | | 
| NVF - Ben G. | Stephen/Rapi | Done |
| NVF - Joe M. | Rapi | | 
| NVF - Sahil | Rapi | |
| NVF - Tanya | Rapi | |
| OSDI | Rapi | Done |
| PhoneYourRep - Matt B. | Rapi | |
| Postal - Jody/Lee | Pamela | Done! 😄 |
| Project Swimmy - Ben | Rapi | Done! 😄 |
| Project Swimmy - Matt M. | Rapi | Done! |
| Project Swimmy - Tino | Rapi | End of Week |
| QuakeWatcher - John/Tad | Pamela | *Reached out to schedule* |
| Reddit - Joseph | Pamela | *Reached out to schedule* | 
| RepresentMe | Pamela/Joe | |
| Resistance Calendar | Pamela/Stephen | Done! 😄 |
| Resistance Toolkit | Stephen | |
| Revolution Hub | Stephen | |
| Run DNC | Pamela | *Reached out to schedule* |
| Sasjkia - Carpool | Rapi | Feb 15 • 6p |
| Single Sign-on - Rabble | Rapi/Pamela | |
| Signal SMS Blast - Rabble/Dave | Pamela | *Reached out to schedule* |
| Social Roots - Ana | Stephen | | 
| Sunoco - Ethan | Pamela | Done! 😄 |
| SwingLeft - Saikat | Stephen | |
| Take2 - Christian | Stephen | |
| Townhall Countdown - Colin/Ethan | Pamela | Done! 😄 |
| UnionBase - Larry | Stephen | |
| WeTrust - Justin | Stephen | |
| WeVote - Dale | Stephen | |
| ~NoSuperPAC~ | Inactive | |
| ~Not Me Us~ | Inactive | |
| ~Political Landscape~ | Inactive | |

**Comment by WoobieTuesday** [comment]
@desmondjones @rapi I updated the list to the best of my recollection and got call from Michael at Village Voice. 

Where I left off: 

* Want to cross-check this list with the Airtable list to make sure we've got everything in here;
* Scour App channels without Leads to see who started the channel/who's working on the project.

**Comment by desmondjones** [comment]
@WoobieTuesday @rapi-progcode 

- Cross-checked this list to the Airtable ProgApps list, adding to each what is necessary to reflect the same "Lead" and "Assigned to" information.  
- Added to the list of coordinators on Airtable ProgApps.

**Comment by rapi-progcode** [comment]
@WoobieTuesday @desmondjones would it be possible if we bring in the newbies instead of the coordinators? Let's pair with them on Wednesday.

**Comment by WoobieTuesday** [comment]
Sure, @rapi! I think that's a really brilliant idea!

**Comment by desmondjones** [comment]
Not sure that I understand.

**Comment by WoobieTuesday** [comment]
@desmondjones Now that the above chart has been filled out, we are reaching out to our app partners to set up 1:1 app partner onboarding meetings to talk about the Goal, Partnerships and upcoming Conferences listed above the chart. @rapi-castillo asked us to try to pair up with them last Wednesday, but so far all of the people I've reached out to have not been available. I am trying again this week.

**Comment by rcscastillo** [comment]
This was good! I think we can have a different process for this.
