### ISSUE TITLE
Hack the Ban

### ISSUE THREAD

**Issue by rapicastillo** [ProgressiveCoders/functions#73]
Light partnership with Leslie from HackTheBan, mainly support on operations and capacity.

**Comment by rapicastillo** [comment]
@progcodepreston @WoobieTuesday from the activities yesterday I hope it's right to assume you're the advocated for HackTheBan in ProgCode  :)

**Comment by WoobieTuesday** [comment]
Works for me! I'm very excited about this project. :0] 👍

**Comment by rapicastillo** [comment]
Closing this one! Great work everyone.
