### ISSUE TITLE
ProgCode.co to ProgCode.org

### ISSUE THREAD

**Issue by rapicastillo** [ProgressiveCoders/functions#78]
Move ProgCode.co to ProgCode.org to become a more official looking and not from UK. 

* ProgCode.co will forward to ProgCode.org

**Comment by rcscastillo** [comment]
Closed!

**Comment by rcscastillo** [comment]
Currently moving emails to .org

**Comment by rapicastillo** [comment]
Closed the issue as we have all been set!
