### ISSUE TITLE
ThoughtWorks Meeting @ Jan 12 • 7pm EST

### ISSUE THREAD

**Issue by rapi-progcode** [ProgressiveCoders/functions#8]
Saron Yitbarek has invited Progressive Coders Network and our partners to attend a gathering of community and tech leaders to discuss how we can go forward in today's society. 

This is going to happen in NYC, at ThoughtWorks offices in Madison and 19th.

More info incoming. Invitations have been sent, please comment or reach out to me if interested to join.

**Comment by schuyler1d** [comment]
yes, please.

**Comment by rapi-progcode** [comment]
@schuyler1d So sorry this was cancelled! :(

**Comment by rapi-progcode** [comment]
The event was moved to a saturday, will create a different card.

Action Item Fair:

https://www.actionitemfair.com/

Thank you!
