### ISSUE TITLE
Connecting a Slack API to Airtable to automatically update the Channel List

### ISSUE THREAD

**Issue by dave-mahler** [ProgressiveCoders/functions#86]
As a staff member I want to export channel info from slack to Airtable so that I can create a more robust channel list that can be more regularly updated.

As a community member I want to see an up-to-date, categorized channel list to help me find channels that I am interested in joining / contributing to.

**Comment by WoobieTuesday** [comment]
### **[ProgCode Staff Onboarding Document](https://docs.google.com/document/d/1qcHPUItSkg9T8YOGANA8fyUsyDNiXs3saIrsdUWyy7U/edit)** created  Feb 23 2017 by @jpb5013

### Purpose

This document provides a brainstorm around the plan for Prog Code Staff onboarding. The goal is to establish a well defined process for community members to understand how to become official Prog Code staff members, including key resources and requirements necessary to operate within the existing structure and processes.

**Comment by jpb5013** [comment]
Think we chatted about this since the issue was created, it'll be good to segue this into the work that @tktino and @rthbound are driving with the Slack archiving solution. Good way to gain some solid momentum and drive effective impact.

**Comment by WoobieTuesday** [comment]
The above comment was supposed to have been made beneath Issue [#87](https://github.com/ProgressiveCoders/functions/issues/87) Not sure how I found myself here after clicking on Dave's link to #87 but I'm 99.9% certain it's user error! So sorry for the confusion.

**Comment by dave-mahler** [comment]
Complete! Hooray!
