### ISSUE TITLE
Remove mentions of supporting PACs at the ProgCode Manifesto

### ISSUE THREAD

**Issue by rapi-castillo** [ProgressiveCoders/functions#88]
Propose to remove parts of ProgCode Manifesto that pertain to supporting candidates. 

**Example:**

> Various groups: Our Revolution, Political Revolution, Brand New Congress, and more, have begun a search for candidates who reflect a progressive platform. 
 
>  Remove: These candidates will not rely on dark money, instead relying on grassroots efforts to help their candidacy. It is our duty, as the tech volunteers who helped build Bernie’s movement, to continue helping these candidates.

Proposal to remove this as we are more focused now with the organizations and grassroots than candidates, partly because of the 501(c)(4) limitation as well. Instead, we will re-word it to focus more on grassroots organizations and 

https://docs.google.com/document/d/1P8iL3kTWO0Y9aYe8lndcUWTJ27BOZyXWwL03LJ3kxT0/edit#

Remain more issue focus.

**Comment by jpb5013** [comment]
Fully agreed. Think it's worth focusing on this as a way to really drive our community decision making process, would be a great topic of conversation for today's staff meeting

**Comment by rcscastillo** [comment]
This has been applied to the ProgCode manifesto. Closing.
