### ISSUE TITLE
Change "Staffer" language to "Volunteer Staffer"

### ISSUE THREAD

**Issue by rapicastillo** [ProgressiveCoders/functions#95]
Specifically in assets such as:

https://medium.com/progressive-coders-network/conduits-of-progressive-technological-change-4ee75f1e373d#.eipn1oukk

**Comment by rcscastillo** [comment]
Sent requests to @jpb5013 to switch code. (We're the only two folks that calls staffers staffers)

**Comment by jpb5013** [comment]
I fixed these during the *volunteer *staff call last Sunday :)

**Comment by rcscastillo** [comment]
Awesome! Closing this now
